### ISSUE TITLE
Dependency on future

### ISSUE THREAD

**Issue by frenzymadness** [zardus/ana#16]
Do you still need to depend on future library? future will no longer work with Python 3.12 because imp module has been removed from stdlib and the situation will be even worse with 3.13 because the lib2to3 which is the core of the future will be removed from stdlib as well.

It should be simple to remove the dependency on future, it's a good idea to do it, and I can help you with that if you want to.

**Comment by zardus** [comment]
ana isn't really used anymore, and I should probably archive this repo. Since it's mostly used to run old versions of angr (on old versions of Python), it's probably best to leave it as is for now.

**Comment by frenzymadness** [comment]
Thank you for the quick reply. We have ana packaged in Fedora so I have to prepare the patch anyway. Should I open a PR?

**Comment by frenzymadness** [comment]
The patch is not complex, see https://src.fedoraproject.org/fork/lbalhar/rpms/python-ana/blob/3ca9be450c68252cff7c803e4679c71a2a536c8b/f/drop-dependency-on-future.patch

**Comment by zardus** [comment]
Oh, neat! Sure, a PR would be great On Jul 23, 2023, at 12:33 AM, frenzymadness ***@***.***> wrote:﻿
The patch is not complex, see https://src.fedoraproject.org/fork/lbalhar/rpms/python-ana/blob/3ca9be450c68252cff7c803e4679c71a2a536c8b/f/drop-dependency-on-future.patch
